[project]
name = "marimo-notebooks"
version = "0.1.0"
description = "Marimo notebooks"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "clean-uk-pv",
    "marimo>=0.13.7",
    "matplotlib>=3.10.3",
]

[tool.uv.sources]
clean-uk-pv = { path = "../" }
